// Auto-generated by scripts/update-wc26-stats.js — do not edit manually
// Last updated: 2026-06-21T11:48:48.949Z
// Processed: 1 matches (0 new this run) · Players: 66
const WC26_PROCESSED = ["FIFA"];
const WC26_STATS = {
  "Julián Quiñones": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Raúl Jiménez": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Hwang In-beom": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Oh Hyeon-gyu": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Michal Sadílek": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Teboho Mokoena": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Cyle Larin": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Breel Embolo": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Vinicius José Paixão de Oliveira Júnior": {
    "apps": 0,
    "goals": 2,
    "assists": 0
  },
  "Ismael Saibari": {
    "apps": 0,
    "goals": 2,
    "assists": 0
  },
  "John McGinn": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Matheus Santos Carneiro Cunha": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Folarin Balogun": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Gio Reyna": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Mauricio": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Nestory Irankunda": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Connor Metcalfe": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Alex Freeman": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Matías Galarza": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Felix Nmecha": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Nico Schlotterbeck": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Kai Havertz": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Jamal Musiala": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Nathaniel Brown": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Deniz Undav": {
    "apps": 0,
    "goals": 2,
    "assists": 0
  },
  "Livano Comenencia": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Amad Diallo": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Franck Kessié": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Virgil van Dijk": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Crysencio Summerville": {
    "apps": 0,
    "goals": 2,
    "assists": 0
  },
  "Keito Nakamura": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Daichi Kamada": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Yasin Ayari": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Alexander Isak": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Viktor Gyökeres": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Mattias Svanberg": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Brian Brobbey": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Cody Gakpo": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Anthony Elanga": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Emam Ashour": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Ramin Rezaiyan": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Eli Just": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Abdulelah Al-Amri": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Maximiliano Araújo": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Kylian Mbappé": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Bradley Barcola": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Ibrahim Mbaye": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Aymen Hussein": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Erling Haaland": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Leo Skiri Østigård": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Lionel Messi": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Romano Schmid": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Ali Olwan": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "João Neves": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Yoann Wissa": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Abbosbek Fayzullaev": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Daniel Muñoz": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Luis Díaz": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Jaminton Campaz": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Harry Kane": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Jude Bellingham": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Marcus Rashford": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Martin Baturina": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Petar Musa": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Caleb Yirenkyi": {
    "apps": 0,
    "goals": 1,
    "assists": 0
  },
  "Kōki Ogawa": {
    "apps": 0,
    "goals": 0,
    "assists": 0
  }
};
