// Auto-generated by scripts/update-wc26-stats.js — do not edit manually
// Last updated: (not yet run)
// Matches processed: 0/0 · Players with data: 0
const WC26_PROCESSED = [];
const WC26_STATS = {};
